---
- name: Restart hostname service
  service: name=hostname state=restarted
  when: initial_run is not defined

- name: Reconfigure keyboard
  shell: "{{ item }}"
  with_items:
    - dpkg-reconfigure -fnoninteractive -pcritical keyboard-configuration
    - setupcon
