---
- name: Get key for gh cli repo
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C99B11DEB97541F0

- name: Get repo for gh cli
  apt_repository:
    repo: deb https://cli.github.com/packages bionic main
    state: present

- name: Install gh cli
  apt:
    name: gh
    update_cache: yes

- name: Get submit command
  git: repo=git://github.com/sebastianstigler/testing_und_debugging_submit.git
    dest=/opt/submit/

- name: Install submit command
  file: src=/opt/submit/{{ submit_command }} dest=/usr/local/bin/submit state=link

- name: Create directory for gpg key
  file: path=/opt/gpg state=directory

- name: Get gpg key
  copy: src=htw.asc dest=/opt/gpg/htw.asc

- name: Install gpg key
  shell: su -c "gpg --import /opt/gpg/htw.asc" - {{ vm_user }}

