---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade
  apt:
    upgrade: dist

- name: Install base packages
  apt: name={{ item }} state={{ install_state }}
  with_items:
    - zip
    - vim
    - cscope
    - exuberant-ctags
    - dos2unix
    - man-db
    - bash-completion
    - language-pack-de
    - language-pack-de-base
    - aptitude

- name: Config vim
  copy: src=vimrc dest=/home/{{ vm_user }}/.vimrc
    owner={{ vm_user }} group={{ vm_group }}

- name: Set hostname
  template: src=hostname.j2 dest=/etc/hostname

- name: Set hostname entry in hosts file
  template: src=hosts.j2 dest=/etc/hosts

- name: Set keyboard
  copy: src=keyboard dest=/etc/default/keyboard
  notify: Reconfigure keyboard

- name: Set Timezone
  timezone: name={{ timezone }}

- name: Create Locale
  locale_gen: name={{ locale }}

- name: set locale
  command: /usr/sbin/update-locale LANG={{ locale }}

- name: dont display some motd messages
  shell: chmod -x /etc/update-motd.d/{{ item }}
  with_items:
    - 90-updates-available
    - 91-release-upgrade
    - 50-motd-news
    - 80-livepatch
