---
- name: Install apache
  apt: name=apache2 state={{ install_state }}

- name: Config apache
  template: src=default.j2 dest=/etc/apache2/sites-available/default
  notify: Reload apache config

- name: Create root directory for apache
  file: path=/home/{{ vm_user }}/project/ state=directory
    owner={{ vm_user }} group={{ vm_group }}

- name: Install index.html
  copy: src=README.html dest=/var/www/index.html
    owner=www-data group=www-data

- name: Install README in root directory
  copy: src=README dest=/home/{{ vm_user }}/project/README 
    owner={{ vm_user }} group={{ vm_group }}
