---

- name: Update setuptools and pip
  pip: name={{ item }} state=latest executable=pip3
  with_items:
    - setuptools

- name: Install configfile for Ipython Notebook
  copy:
    src=requirements3.txt
    dest=/tmp/requirements3.txt

- name: Install necessary pip packages for IPython
  pip: requirements=/tmp/requirements3.txt state={{ install_state }} executable=pip3

- name: Create config directory for Ipython 
  file:
    path=/home/{{ vm_user }}/.jupyter/
    state=directory
    mode=0755
    owner={{ vm_user }}
    group={{ vm_group }}

- name: Install configfile for Ipython Notebook
  copy:
    src=jupyter_notebook_config.py
    dest=/home/{{ vm_user }}/.jupyter/jupyter_notebook_config.py
    mode=0644
    owner={{ vm_user }}
    group={{ vm_group }}
