---
- name: Install necessary apt packages for IPython
  apt: name={{ item }} state={{ install_state }}
  with_items:
    - zlib1g-dev
    - libzmq-dev
    - sqlite3
    - libsqlite3-dev
    - libcurl4-openssl-dev

- name: Install necessary pip packages for IPython
  pip: name={{ item }} state={{ install_state }}
  with_items:
    - tornado
    - pyzmq
    - jsonshema
    - mistune
    - mock
    - ipython[notebook]
