---
- name: Install necessary apt packages for IPython
  apt: name={{ item }} state={{ install_state }}
  with_items:
    - zlib1g-dev
    - libzmq-dev
    - sqlite3
    - libsqlite3-dev
    - libcurl4-openssl-dev

- name: Update setuptools and pip
  pip: name={{ item }} state=latest
  with_items:
    - setuptools
    - pip

- name: Install necessary pip packages for IPython
  pip: name={{ item }} state={{ install_state }}
  with_items:
    - tornado
    - pyzmq
    - jsonschema
    - mistune
    - mock
    - terminado
    - ipython[notebook]
    - jupyter

- name: Create config directory for Ipython 
  file:
    path=/home/{{ vm_user }}/.ipython/profile_default/
    state=directory
    mode=0755
    owner={{ vm_user }}
    group={{ vm_group }}

- name: Install configfile for Ipython Notebook
  copy:
    src=ipython_notebook_config.py
    dest=/home/{{ vm_user }}/.ipython/profile_default/ipython_notebook_config.py
    mode=0644
    owner={{ vm_user }}
    group={{ vm_group }}
